DEFAULT_BANKS = [
    {
        "name": "Unit 11 健康與醫療",
        "sentences": [
            {"english": "I need a prescription.", "chinese": "我需要一張處方。"},
            {"english": "The doctor is writing a prescription.", "chinese": "醫生正在開處方箋。"},
            {"english": "Does this medicine have side effects?", "chinese": "這種藥物有副作用嗎？"},
            {"english": "Take this medicine after meals.", "chinese": "飯後服用這種藥。"},
            {"english": "I have a terrible headache.", "chinese": "我頭痛得很厲害。"},
            {"english": "You should get some rest.", "chinese": "你應該多休息。"},
            {"english": "The nurse is taking his temperature.", "chinese": "護理師正在量他的體溫。"},
            {"english": "I want to make an appointment with Dr. Smith.", "chinese": "我想預約史密斯醫生的門診。"},
        ],
    },
    {
        "name": "Unit 1 日常生活英語",
        "sentences": [
            {"english": "What time do you usually wake up?", "chinese": "你通常幾點起床？"},
            {"english": "I need to wash my car this weekend.", "chinese": "我這週末需要洗車。"},
            {"english": "Could you pass me the salt, please?", "chinese": "請把鹽遞給我好嗎？"},
            {"english": "I am looking forward to our trip.", "chinese": "我非常期待我們的旅行。"},
            {"english": "Don't forget to lock the door.", "chinese": "別忘了鎖門。"},
            {"english": "It is going to rain this afternoon.", "chinese": "今天下午要下雨了。"},
        ],
    },
    {
        "name": "Unit 21 基礎越南語交流",
        "language": "vi",
        "sentences": [
            {"english": "Xin chào, bạn khỏe không?", "chinese": "你好，你好嗎？"},
            {"english": "Tôi tên là Minh, rất vui được gặp bạn.", "chinese": "我名字叫 Minh，很高興見到你。"},
            {"english": "Bạn là người nước nào?", "chinese": "你是哪國人？"},
            {"english": "Tôi là người Đài Loan.", "chinese": "我是台灣人。"},
            {"english": "Hẹn gặp lại bạn vào ngày mai.", "chinese": "明天見。"},
            {"english": "Cảm ơn bạn vì tất cả mọi thứ.", "chinese": "謝謝你所做的一切。"},
            {"english": "Bạn có thể giúp tôi một chút không?", "chinese": "你能幫我一下嗎？"},
            {"english": "Xin lỗi, tôi không hiểu bạn nói gì.", "chinese": "對不起，我不懂你說什麼。"},
        ],
    },
    {
        "name": "Unit 22 越南生活與餐飲",
        "language": "vi",
        "sentences": [
            {"english": "Tôi muốn ăn phở bò.", "chinese": "我想吃牛肉河粉。"},
            {"english": "Cho tôi xin một ly cà phê sữa đá.", "chinese": "請給我一杯冰奶咖啡。"},
            {"english": "Cái này giá bao nhiêu tiền?", "chinese": "這個多少錢？"},
            {"english": "Nhà vệ sinh ở đâu vậy?", "chinese": "洗手間在哪裡？"},
            {"english": "Món ăn này rất ngon.", "chinese": "這道菜非常好吃。"},
            {"english": "Tôi thích đi du lịch ở Việt Nam.", "chinese": "我喜歡去越南旅遊。"},
            {"english": "Thời tiết hôm nay rất nóng.", "chinese": "今天天氣很熱。"},
            {"english": "Chúc ngủ ngon và có những giấc mơ đẹp.", "chinese": "晚安，祝你有個美夢。"},
        ],
    },
    {
        "name": "Unit 23 電梯遇鄰與日常通勤",
        "language": "vi",
        "sentences": [
            {"english": "Chào anh, anh lên tầng mấy?", "chinese": "你好（哥），你上幾樓？"},
            {"english": "Chào chị, chị xuống tầng một phải không?", "chinese": "你好（姐），妳是下到一樓嗎？"},
            {"english": "Nhờ anh ấn hộ tôi tầng mười lăm nhé.", "chinese": "麻煩你幫我按一下十五樓。"},
            {"english": "Nhờ chị bấm giúp tôi tầng hầm B1.", "chinese": "麻煩妳幫我按一下地下室 B1。"},
            {"english": "Hôm nay anh đi làm sớm thế?", "chinese": "你今天這麼早去上班啊？"},
            {"english": "Hôm nay chị về muộn thế?", "chinese": "妳今天這麼晚才回來呀？"},
            {"english": "Bên ngoài đang mưa to lắm, anh nhớ mang ô.", "chinese": "外面正在下大雨，你記得帶傘。"},
            {"english": "Hôm nay trời nóng quá anh nhỉ.", "chinese": "今天天氣真熱啊，對吧？"},
            {"english": "Trời sắp mưa rồi, anh đi cẩn thận nhé.", "chinese": "快要下雨了，你路上小心喔。"},
            {"english": "Anh đi làm bằng xe máy hay ô tô?", "chinese": "你騎摩托車還是開車上班？"},
            {"english": "Giờ này ngoài đường tắc đường lắm.", "chinese": "這個時間外面路上很塞車。"},
            {"english": "Tôi đi làm bằng xe buýt cho tiện.", "chinese": "我搭公車上班比較方便。"},
            {"english": "Tôi đi Grab cho nhanh, đỡ phải gửi xe.", "chinese": "我搭 Grab 比較快，省得停車。"},
            {"english": "Anh mới đi siêu thị về à?", "chinese": "你剛去超市回來嗎？"},
            {"english": "Tôi đi mua ít đồ ăn cho bữa tối.", "chinese": "我去買點晚餐用的食材。"},
            {"english": "Chị đi đổ rác à?", "chinese": "妳去倒垃圾嗎？"},
            {"english": "Thang máy hôm nay chạy hơi chậm.", "chinese": "今天的電梯運作得有點慢。"},
            {"english": "Thang máy đang bảo trì một bên.", "chinese": "電梯有一邊正在保養維修。"},
            {"english": "Hôm nay chung cư đông người quá.", "chinese": "今天公寓大樓人真多。"},
            {"english": "Anh dắt chó đi dạo à?", "chinese": "你帶狗去散步嗎？"},
            {"english": "Con chó của anh đáng yêu quá.", "chinese": "你的狗真可愛。"},
            {"english": "Hôm nay anh được nghỉ làm à?", "chinese": "你今天放假不用上班嗎？"},
            {"english": "Vâng, hôm nay là cuối tuần của tôi.", "chinese": "對，今天是我週末假。"},
            {"english": "Chị đi đón con đi học về à?", "chinese": "妳去接小孩放學嗎？"},
            {"english": "Cháu nhà chị năm nay học lớp mấy rồi?", "chinese": "妳家小孩今年上幾年級了？"},
            {"english": "Anh có mang thẻ cư dân chưa?", "chinese": "你帶住戶卡了嗎？"},
            {"english": "Suýt nữa thì tôi quên mang thẻ thang máy.", "chinese": "我差點忘了帶電梯卡。"},
            {"english": "Để tôi giữ cửa thang máy cho anh.", "chinese": "我幫你扶著電梯門。"},
            {"english": "Cứ vào đi anh, vẫn còn chỗ.", "chinese": "進來吧，還有空間。"},
            {"english": "Thang máy đủ chỗ cho mọi người không?", "chinese": "電梯容得下大家嗎？"},
            {"english": "Hình như thang máy bị quá tải rồi.", "chinese": "電梯好像超載了。"},
            {"english": "Anh xuống hầm gửi xe à?", "chinese": "你下去地下室停車場嗎？"},
            {"english": "Vâng, tôi xuống lấy xe máy.", "chinese": "對，我下去牽摩托車。"},
            {"english": "Anh đi làm ở quận mấy?", "chinese": "你在第幾區上班？"},
            {"english": "Tôi đi làm ở trung tâm thành phố.", "chinese": "我在市中心上班。"},
            {"english": "Đoạn đường đó hay bị kẹt xe vào giờ cao điểm.", "chinese": "那段路在尖峰時間很容易塞車。"},
            {"english": "Tôi thường đi làm sớm để tránh tắc đường.", "chinese": "我通常提早出門以避開塞車。"},
            {"english": "Anh đi công tác mới về à?", "chinese": "你剛出差回來嗎？"},
            {"english": "Vâng, tôi vừa từ sân bay về.", "chinese": "對，我剛從機場回來。"},
            {"english": "Anh xách đồ nặng thế, để tôi xách hộ một tay.", "chinese": "你拿那麼重的東西，我幫你拿一手吧。"},
            {"english": "Không sao đâu, tôi tự xách được, cảm ơn anh.", "chinese": "沒關係，我自己拿得動，謝謝你。"},
            {"english": "Hẹn gặp lại anh sau nhé.", "chinese": "晚點見囉。"},
            {"english": "Chúc anh một ngày làm việc vui vẻ.", "chinese": "祝你工作愉快。"},
            {"english": "Chúc chị cuối tuần vui vẻ.", "chinese": "祝妳週末愉快。"},
            {"english": "Chào anh nhé, tôi đến tầng của tôi rồi.", "chinese": "我到了，先走囉。"},
            {"english": "Chúc anh ăn tối ngon miệng.", "chinese": "祝你晚餐愉快。"},
            {"english": "Tối nay anh có đi tập thể dục không?", "chinese": "你今天晚上去運動嗎？"},
            {"english": "Tôi hay chạy bộ ở công viên dưới nhà.", "chinese": "我經常在樓下的公園跑步。"},
            {"english": "Khi nào rảnh qua nhà tôi uống trà nhé.", "chinese": "有空來我家喝茶喔。"},
            {"english": "Cảm ơn anh, hàng xóm tốt bụng.", "chinese": "謝謝你，好鄰居。"},
        ],
    },
    {
        "name": "Unit 24 電梯極簡短對話",
        "language": "vi",
        "sentences": [
            {"english": "Chào anh.", "chinese": "你好（哥）。"},
            {"english": "Chào chị.", "chinese": "你好（姐）。"},
            {"english": "Lên hay xuống?", "chinese": "上還是下？"},
            {"english": "Tôi đi lên.", "chinese": "我上去。"},
            {"english": "Tôi đi xuống.", "chinese": "我下去。"},
            {"english": "Tầng mấy ạ?", "chinese": "幾樓呢？"},
            {"english": "Tầng mười nhé.", "chinese": "十樓喔。"},
            {"english": "Cảm ơn anh.", "chinese": "謝謝你（哥）。"},
            {"english": "Cảm ơn chị.", "chinese": "謝謝妳（姐）。"},
            {"english": "Đến rồi.", "chinese": "到了。"},
            {"english": "Tôi ra đây.", "chinese": "我出去了。"},
            {"english": "Đi làm à?", "chinese": "去上班嗎？"},
            {"english": "Về rồi à?", "chinese": "回來啦？"},
            {"english": "Đúng thế.", "chinese": "是的/沒錯。"},
            {"english": "Trời mưa rồi.", "chinese": "下雨了。"},
            {"english": "Nóng quá.", "chinese": "好熱。"},
            {"english": "Lạnh quá.", "chinese": "好冷。"},
            {"english": "Đông quá nhỉ.", "chinese": "人真多。"},
            {"english": "Cho tôi qua.", "chinese": "請讓我過一下。"},
            {"english": "Mời vào.", "chinese": "請進。"},
            {"english": "Giữ cửa nhé.", "chinese": "幫忙扶門喔。"},
            {"english": "Thả cửa ra.", "chinese": "放開門吧。"},
            {"english": "Đi cẩn thận.", "chinese": "慢走/路上小心。"},
            {"english": "Hẹn gặp lại.", "chinese": "再見。"},
            {"english": "Ngày mới tốt lành.", "chinese": "祝新的一天美好。"},
            {"english": "Bận quá.", "chinese": "好忙。"},
            {"english": "Mệt quá.", "chinese": "好累。"},
            {"english": "Muộn rồi.", "chinese": "遲到了。"},
            {"english": "Nhanh lên.", "chinese": "快一點。"},
            {"english": "Chờ tôi với.", "chinese": "等等我。"},
            {"english": "Tầng hầm B1.", "chinese": "地下室 B1。"},
            {"english": "Tầng một.", "chinese": "一樓。"},
            {"english": "Tầng mười hai.", "chinese": "十二樓。"},
            {"english": "Tầng trệt.", "chinese": "一樓/地面層。"},
            {"english": "Quên thẻ rồi.", "chinese": "忘記帶卡了。"},
            {"english": "Để tôi bấm.", "chinese": "我來按。"},
            {"english": "Anh trước đi.", "chinese": "你先請。"},
            {"english": "Chị trước đi.", "chinese": "妳先請。"},
            {"english": "Không sao đâu.", "chinese": "沒關係。"},
            {"english": "Dạ, đúng rồi.", "chinese": "是的，對了。"},
            {"english": "Chào buổi sáng.", "chinese": "早安。"},
            {"english": "Chào buổi tối.", "chinese": "晚安。"},
            {"english": "Chúc ngủ ngon.", "chinese": "晚安/祝好眠。"},
            {"english": "Đi chơi à?", "chinese": "去玩嗎？"},
            {"english": "Đi mua đồ.", "chinese": "去買東西。"},
            {"english": "Về nhà thôi.", "chinese": "回家吧。"},
            {"english": "Nước ngập rồi.", "chinese": "淹水了。"},
            {"english": "Tắc đường quá.", "chinese": "太塞車了。"},
            {"english": "Grab đến chưa?", "chinese": "Grab 到了嗎？"},
            {"english": "Tôi đi đây.", "chinese": "我走囉。"},
        ],
    },
    {
        "name": "Unit 25 岳母來家做月子",
        "language": "vi",
        "sentences": [
            {"english": "Mẹ vợ tôi sắp đến nhà chơi rồi.", "chinese": "我岳母快要來家裡了。"},
            {"english": "Mẹ sang đây để giúp vợ tôi ở cữ.", "chinese": "媽媽過來是為了幫我老婆坐月子。"},
            {"english": "Mẹ chuẩn bị nhiều đồ bổ lắm.", "chinese": "媽媽準備了很多補品。"},
            {"english": "Em đã chuẩn bị phòng cho mẹ chưa?", "chinese": "妳把給媽媽的房間準備好了嗎？"},
            {"english": "Em dọn dẹp phòng khách sạch sẽ rồi.", "chinese": "我把客房打掃乾淨了。"},
            {"english": "Con chào mẹ, mẹ đi đường có mệt không?", "chinese": "媽您好，您一路上累不累？"},
            {"english": "Mẹ đem theo gà ác và nhân sâm sang.", "chinese": "媽媽帶了烏骨雞和人參過來。"},
            {"english": "Phụ nữ ở cữ cần giữ ấm cơ thể.", "chinese": "坐月子的女人需要保持身體溫暖。"},
            {"english": "Không được tắm nước lạnh đâu nhé.", "chinese": "絕對不能洗冷水澡喔。"},
            {"english": "Mẹ sẽ nấu canh móng giò hầm đu đủ.", "chinese": "媽媽會煮木瓜燉豬腳湯。"},
            {"english": "Món này rất tốt cho sữa mẹ.", "chinese": "這道菜對母乳非常好。"},
            {"english": "Vợ tôi cần được nghỉ ngơi nhiều hơn.", "chinese": "我老婆需要多休息。"},
            {"english": "Đỡ đẻ xong phải kiêng khem cẩn thận.", "chinese": "生完小孩後必須小心忌口。"},
            {"english": "Con cứ để mẹ bế cháu cho.", "chinese": "你把抱小孩的事交給媽媽吧。"},
            {"english": "Trộm vía em bé ngủ ngon quá.", "chinese": "謝天謝地，寶寶睡得真香。"},
            {"english": "Để con đi mua thêm sữa và tã giấy.", "chinese": "我去多買些奶粉和尿布。"},
            {"english": "Mẹ nấu ăn ngon quá, con cảm ơn mẹ.", "chinese": "媽媽煮飯真好吃，謝謝媽媽。"},
            {"english": "Đừng để gió lùa vào phòng vợ con nhé.", "chinese": "別讓風吹進你老婆的房間喔。"},
            {"english": "Vợ tôi không được dùng điện thoại nhiều.", "chinese": "我老婆不能用太多手機。"},
            {"english": "Mẹ sẽ giúp chăm em bé vào ban đêm.", "chinese": "媽媽會在晚上幫忙照顧寶寶。"},
            {"english": "Vợ chồng con cảm ơn mẹ nhiều lắm.", "chinese": "我們夫妻倆非常感謝媽媽。"},
            {"english": "Con nhớ giặt quần áo cho vợ bằng nước ấm.", "chinese": "你記得用溫水幫老婆洗衣服。"},
            {"english": "Mẹ pha nước gừng ấm cho vợ con ngâm chân.", "chinese": "媽媽泡了溫薑水給你老婆泡腳。"},
            {"english": "Bác sĩ nói sức khỏe của vợ con đang tốt lên.", "chinese": "醫生說你老婆的身體正在好轉。"},
            {"english": "Em bé bú sữa mẹ hoàn toàn chứ?", "chinese": "寶寶是完全全母乳餵養嗎？"},
            {"english": "Con sẽ học cách thay tã cho em bé.", "chinese": "我會學習怎麼幫寶寶換尿布。"},
            {"english": "Cơm ở cữ mẹ nấu rất thanh đạm.", "chinese": "媽媽煮的月子餐非常清淡。"},
            {"english": "Nhà mình nhộn nhịp hơn từ khi có mẹ sang.", "chinese": "自從媽媽過來，我們家變得熱鬧多了。"},
            {"english": "Mẹ nhớ giữ gìn sức khỏe, đừng mệt quá nhé.", "chinese": "媽您也記得保重身體，別太累了喔。"},
            {"english": "Có mẹ ở đây, con yên tâm đi làm rồi.", "chinese": "有媽媽在這裡，我就可以安心去上班了。"},
        ],
    },
]
